### ISSUE TITLE
Prepending page titles

### ISSUE THREAD

**Issue by danhalliday** [reshape/layouts#23]
As far as I can tell, the example given in the readme to prepend a title doesn't work:

    <block name="title" type="prepend">How to use reshape-layouts</block>

If I write it as above, I get no title element, and the plain text appears at the beginning of the body. If I write it as follows with a title element:

    <block name="title" type="prepend"><title>How to use reshape-layouts</title></block>

It produces two title tags, one from the layout and one from the child template. Am I missing something?

**Comment by jescalan** [comment]
Ah yes I'm sorry - the title tag requires some special treatment because of the way its handled by the html parser, and this example won't work. Let me update this.

**Comment by jescalan** [comment]
Done! Sorry for the inconsistency.
